# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-added-large-files
        args: ["--maxkb=250"]
        exclude: ^uv\.lock$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        stages: [pre-commit]
        exclude: 'tests/jwt\.txt'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.15.8"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [.]
        pass_filenames: false
        additional_dependencies:
          [pydantic>=2.0.0, types-protobuf, types-toml]
  - repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: tests
        name: tests
        stages: [pre-push]
        language: system
        entry: uv run pytest tests/test_frontend_client.py tests/test_tcpb_client.py tests/test_utils.py
        types: [python]
        pass_filenames: false
