// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: terachem_server.proto

#ifndef PROTOBUF_terachem_5fserver_2eproto__INCLUDED
#define PROTOBUF_terachem_5fserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace terachem_server {
class JobInput;
class JobInputDefaultTypeInternal;
extern JobInputDefaultTypeInternal _JobInput_default_instance_;
class JobOutput;
class JobOutputDefaultTypeInternal;
extern JobOutputDefaultTypeInternal _JobOutput_default_instance_;
class Mol;
class MolDefaultTypeInternal;
extern MolDefaultTypeInternal _Mol_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace terachem_server

namespace terachem_server {

namespace protobuf_terachem_5fserver_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_terachem_5fserver_2eproto

enum Mol_UnitType {
  Mol_UnitType_ANGSTROM = 0,
  Mol_UnitType_BOHR = 1,
  Mol_UnitType_Mol_UnitType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Mol_UnitType_Mol_UnitType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Mol_UnitType_IsValid(int value);
const Mol_UnitType Mol_UnitType_UnitType_MIN = Mol_UnitType_ANGSTROM;
const Mol_UnitType Mol_UnitType_UnitType_MAX = Mol_UnitType_BOHR;
const int Mol_UnitType_UnitType_ARRAYSIZE = Mol_UnitType_UnitType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Mol_UnitType_descriptor();
inline const ::std::string& Mol_UnitType_Name(Mol_UnitType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Mol_UnitType_descriptor(), value);
}
inline bool Mol_UnitType_Parse(
    const ::std::string& name, Mol_UnitType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Mol_UnitType>(
    Mol_UnitType_descriptor(), name, value);
}
enum JobInput_RunType {
  JobInput_RunType_ENERGY = 0,
  JobInput_RunType_GRADIENT = 1,
  JobInput_RunType_JobInput_RunType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  JobInput_RunType_JobInput_RunType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool JobInput_RunType_IsValid(int value);
const JobInput_RunType JobInput_RunType_RunType_MIN = JobInput_RunType_ENERGY;
const JobInput_RunType JobInput_RunType_RunType_MAX = JobInput_RunType_GRADIENT;
const int JobInput_RunType_RunType_ARRAYSIZE = JobInput_RunType_RunType_MAX + 1;

const ::google::protobuf::EnumDescriptor* JobInput_RunType_descriptor();
inline const ::std::string& JobInput_RunType_Name(JobInput_RunType value) {
  return ::google::protobuf::internal::NameOfEnum(
    JobInput_RunType_descriptor(), value);
}
inline bool JobInput_RunType_Parse(
    const ::std::string& name, JobInput_RunType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JobInput_RunType>(
    JobInput_RunType_descriptor(), name, value);
}
enum JobInput_MethodType {
  JobInput_MethodType_HF = 0,
  JobInput_MethodType_CASE = 2,
  JobInput_MethodType_SVWN1 = 3,
  JobInput_MethodType_SVWN3 = 4,
  JobInput_MethodType_SVWN5 = 5,
  JobInput_MethodType_SVWN = 5,
  JobInput_MethodType_B3LYP1 = 6,
  JobInput_MethodType_B3LYP = 6,
  JobInput_MethodType_B3LYP3 = 7,
  JobInput_MethodType_B3LYP5 = 8,
  JobInput_MethodType_BLYP = 9,
  JobInput_MethodType_BHANDHLYP = 10,
  JobInput_MethodType_PBE = 11,
  JobInput_MethodType_REVPBE = 12,
  JobInput_MethodType_PBE0 = 13,
  JobInput_MethodType_REVPBE0 = 14,
  JobInput_MethodType_WPBE = 15,
  JobInput_MethodType_WPBEH = 16,
  JobInput_MethodType_BOP = 17,
  JobInput_MethodType_MUBOP = 18,
  JobInput_MethodType_CAMB3LYP = 19,
  JobInput_MethodType_B97 = 20,
  JobInput_MethodType_WB97 = 21,
  JobInput_MethodType_WB97X = 22,
  JobInput_MethodType_JobInput_MethodType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  JobInput_MethodType_JobInput_MethodType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool JobInput_MethodType_IsValid(int value);
const JobInput_MethodType JobInput_MethodType_MethodType_MIN = JobInput_MethodType_HF;
const JobInput_MethodType JobInput_MethodType_MethodType_MAX = JobInput_MethodType_WB97X;
const int JobInput_MethodType_MethodType_ARRAYSIZE = JobInput_MethodType_MethodType_MAX + 1;

const ::google::protobuf::EnumDescriptor* JobInput_MethodType_descriptor();
inline const ::std::string& JobInput_MethodType_Name(JobInput_MethodType value) {
  return ::google::protobuf::internal::NameOfEnum(
    JobInput_MethodType_descriptor(), value);
}
inline bool JobInput_MethodType_Parse(
    const ::std::string& name, JobInput_MethodType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JobInput_MethodType>(
    JobInput_MethodType_descriptor(), name, value);
}
enum MessageType {
  STATUS = 0,
  MOL = 1,
  JOBINPUT = 2,
  JOBOUTPUT = 3,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = STATUS;
const MessageType MessageType_MAX = JOBOUTPUT;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:terachem_server.Status) */ {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Status& default_instance();

  enum JobStatusCase {
    kAccepted = 2,
    kWorking = 3,
    kCompleted = 4,
    JOB_STATUS_NOT_SET = 0,
  };

  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Status* other);

  // implements Message ----------------------------------------------

  inline Status* New() const PROTOBUF_FINAL { return New(NULL); }

  Status* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool busy = 1;
  void clear_busy();
  static const int kBusyFieldNumber = 1;
  bool busy() const;
  void set_busy(bool value);

  // bool accepted = 2;
  private:
  bool has_accepted() const;
  public:
  void clear_accepted();
  static const int kAcceptedFieldNumber = 2;
  bool accepted() const;
  void set_accepted(bool value);

  // bool working = 3;
  private:
  bool has_working() const;
  public:
  void clear_working();
  static const int kWorkingFieldNumber = 3;
  bool working() const;
  void set_working(bool value);

  // bool completed = 4;
  private:
  bool has_completed() const;
  public:
  void clear_completed();
  static const int kCompletedFieldNumber = 4;
  bool completed() const;
  void set_completed(bool value);

  JobStatusCase job_status_case() const;
  // @@protoc_insertion_point(class_scope:terachem_server.Status)
 private:
  void set_has_accepted();
  void set_has_working();
  void set_has_completed();

  inline bool has_job_status() const;
  void clear_job_status();
  inline void clear_has_job_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool busy_;
  union JobStatusUnion {
    JobStatusUnion() {}
    bool accepted_;
    bool working_;
    bool completed_;
  } job_status_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct protobuf_terachem_5fserver_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Mol : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:terachem_server.Mol) */ {
 public:
  Mol();
  virtual ~Mol();

  Mol(const Mol& from);

  inline Mol& operator=(const Mol& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Mol& default_instance();

  static inline const Mol* internal_default_instance() {
    return reinterpret_cast<const Mol*>(
               &_Mol_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Mol* other);

  // implements Message ----------------------------------------------

  inline Mol* New() const PROTOBUF_FINAL { return New(NULL); }

  Mol* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Mol& from);
  void MergeFrom(const Mol& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Mol* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Mol_UnitType UnitType;
  static const UnitType ANGSTROM =
    Mol_UnitType_ANGSTROM;
  static const UnitType BOHR =
    Mol_UnitType_BOHR;
  static inline bool UnitType_IsValid(int value) {
    return Mol_UnitType_IsValid(value);
  }
  static const UnitType UnitType_MIN =
    Mol_UnitType_UnitType_MIN;
  static const UnitType UnitType_MAX =
    Mol_UnitType_UnitType_MAX;
  static const int UnitType_ARRAYSIZE =
    Mol_UnitType_UnitType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  UnitType_descriptor() {
    return Mol_UnitType_descriptor();
  }
  static inline const ::std::string& UnitType_Name(UnitType value) {
    return Mol_UnitType_Name(value);
  }
  static inline bool UnitType_Parse(const ::std::string& name,
      UnitType* value) {
    return Mol_UnitType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated string atoms = 1;
  int atoms_size() const;
  void clear_atoms();
  static const int kAtomsFieldNumber = 1;
  const ::std::string& atoms(int index) const;
  ::std::string* mutable_atoms(int index);
  void set_atoms(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_atoms(int index, ::std::string&& value);
  #endif
  void set_atoms(int index, const char* value);
  void set_atoms(int index, const char* value, size_t size);
  ::std::string* add_atoms();
  void add_atoms(const ::std::string& value);
  #if LANG_CXX11
  void add_atoms(::std::string&& value);
  #endif
  void add_atoms(const char* value);
  void add_atoms(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& atoms() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_atoms();

  // repeated double xyz = 2;
  int xyz_size() const;
  void clear_xyz();
  static const int kXyzFieldNumber = 2;
  double xyz(int index) const;
  void set_xyz(int index, double value);
  void add_xyz(double value);
  const ::google::protobuf::RepeatedField< double >&
      xyz() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_xyz();

  // .terachem_server.Mol.UnitType units = 3;
  void clear_units();
  static const int kUnitsFieldNumber = 3;
  ::terachem_server::Mol_UnitType units() const;
  void set_units(::terachem_server::Mol_UnitType value);

  // int32 charge = 4;
  void clear_charge();
  static const int kChargeFieldNumber = 4;
  ::google::protobuf::int32 charge() const;
  void set_charge(::google::protobuf::int32 value);

  // int32 multiplicity = 5;
  void clear_multiplicity();
  static const int kMultiplicityFieldNumber = 5;
  ::google::protobuf::int32 multiplicity() const;
  void set_multiplicity(::google::protobuf::int32 value);

  // bool closed = 6;
  void clear_closed();
  static const int kClosedFieldNumber = 6;
  bool closed() const;
  void set_closed(bool value);

  // bool restricted = 7;
  void clear_restricted();
  static const int kRestrictedFieldNumber = 7;
  bool restricted() const;
  void set_restricted(bool value);

  // @@protoc_insertion_point(class_scope:terachem_server.Mol)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> atoms_;
  ::google::protobuf::RepeatedField< double > xyz_;
  mutable int _xyz_cached_byte_size_;
  int units_;
  ::google::protobuf::int32 charge_;
  ::google::protobuf::int32 multiplicity_;
  bool closed_;
  bool restricted_;
  mutable int _cached_size_;
  friend struct protobuf_terachem_5fserver_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class JobInput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:terachem_server.JobInput) */ {
 public:
  JobInput();
  virtual ~JobInput();

  JobInput(const JobInput& from);

  inline JobInput& operator=(const JobInput& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JobInput& default_instance();

  static inline const JobInput* internal_default_instance() {
    return reinterpret_cast<const JobInput*>(
               &_JobInput_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(JobInput* other);

  // implements Message ----------------------------------------------

  inline JobInput* New() const PROTOBUF_FINAL { return New(NULL); }

  JobInput* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JobInput& from);
  void MergeFrom(const JobInput& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JobInput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef JobInput_RunType RunType;
  static const RunType ENERGY =
    JobInput_RunType_ENERGY;
  static const RunType GRADIENT =
    JobInput_RunType_GRADIENT;
  static inline bool RunType_IsValid(int value) {
    return JobInput_RunType_IsValid(value);
  }
  static const RunType RunType_MIN =
    JobInput_RunType_RunType_MIN;
  static const RunType RunType_MAX =
    JobInput_RunType_RunType_MAX;
  static const int RunType_ARRAYSIZE =
    JobInput_RunType_RunType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RunType_descriptor() {
    return JobInput_RunType_descriptor();
  }
  static inline const ::std::string& RunType_Name(RunType value) {
    return JobInput_RunType_Name(value);
  }
  static inline bool RunType_Parse(const ::std::string& name,
      RunType* value) {
    return JobInput_RunType_Parse(name, value);
  }

  typedef JobInput_MethodType MethodType;
  static const MethodType HF =
    JobInput_MethodType_HF;
  static const MethodType CASE =
    JobInput_MethodType_CASE;
  static const MethodType SVWN1 =
    JobInput_MethodType_SVWN1;
  static const MethodType SVWN3 =
    JobInput_MethodType_SVWN3;
  static const MethodType SVWN5 =
    JobInput_MethodType_SVWN5;
  static const MethodType SVWN =
    JobInput_MethodType_SVWN;
  static const MethodType B3LYP1 =
    JobInput_MethodType_B3LYP1;
  static const MethodType B3LYP =
    JobInput_MethodType_B3LYP;
  static const MethodType B3LYP3 =
    JobInput_MethodType_B3LYP3;
  static const MethodType B3LYP5 =
    JobInput_MethodType_B3LYP5;
  static const MethodType BLYP =
    JobInput_MethodType_BLYP;
  static const MethodType BHANDHLYP =
    JobInput_MethodType_BHANDHLYP;
  static const MethodType PBE =
    JobInput_MethodType_PBE;
  static const MethodType REVPBE =
    JobInput_MethodType_REVPBE;
  static const MethodType PBE0 =
    JobInput_MethodType_PBE0;
  static const MethodType REVPBE0 =
    JobInput_MethodType_REVPBE0;
  static const MethodType WPBE =
    JobInput_MethodType_WPBE;
  static const MethodType WPBEH =
    JobInput_MethodType_WPBEH;
  static const MethodType BOP =
    JobInput_MethodType_BOP;
  static const MethodType MUBOP =
    JobInput_MethodType_MUBOP;
  static const MethodType CAMB3LYP =
    JobInput_MethodType_CAMB3LYP;
  static const MethodType B97 =
    JobInput_MethodType_B97;
  static const MethodType WB97 =
    JobInput_MethodType_WB97;
  static const MethodType WB97X =
    JobInput_MethodType_WB97X;
  static inline bool MethodType_IsValid(int value) {
    return JobInput_MethodType_IsValid(value);
  }
  static const MethodType MethodType_MIN =
    JobInput_MethodType_MethodType_MIN;
  static const MethodType MethodType_MAX =
    JobInput_MethodType_MethodType_MAX;
  static const int MethodType_ARRAYSIZE =
    JobInput_MethodType_MethodType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MethodType_descriptor() {
    return JobInput_MethodType_descriptor();
  }
  static inline const ::std::string& MethodType_Name(MethodType value) {
    return JobInput_MethodType_Name(value);
  }
  static inline bool MethodType_Parse(const ::std::string& name,
      MethodType* value) {
    return JobInput_MethodType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated double guess_mo_coeffs_a = 5;
  int guess_mo_coeffs_a_size() const;
  void clear_guess_mo_coeffs_a();
  static const int kGuessMoCoeffsAFieldNumber = 5;
  double guess_mo_coeffs_a(int index) const;
  void set_guess_mo_coeffs_a(int index, double value);
  void add_guess_mo_coeffs_a(double value);
  const ::google::protobuf::RepeatedField< double >&
      guess_mo_coeffs_a() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_guess_mo_coeffs_a();

  // repeated double guess_mo_coeffs_b = 6;
  int guess_mo_coeffs_b_size() const;
  void clear_guess_mo_coeffs_b();
  static const int kGuessMoCoeffsBFieldNumber = 6;
  double guess_mo_coeffs_b(int index) const;
  void set_guess_mo_coeffs_b(int index, double value);
  void add_guess_mo_coeffs_b(double value);
  const ::google::protobuf::RepeatedField< double >&
      guess_mo_coeffs_b() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_guess_mo_coeffs_b();

  // repeated string user_options = 7;
  int user_options_size() const;
  void clear_user_options();
  static const int kUserOptionsFieldNumber = 7;
  const ::std::string& user_options(int index) const;
  ::std::string* mutable_user_options(int index);
  void set_user_options(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_user_options(int index, ::std::string&& value);
  #endif
  void set_user_options(int index, const char* value);
  void set_user_options(int index, const char* value, size_t size);
  ::std::string* add_user_options();
  void add_user_options(const ::std::string& value);
  #if LANG_CXX11
  void add_user_options(::std::string&& value);
  #endif
  void add_user_options(const char* value);
  void add_user_options(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& user_options() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_user_options();

  // string basis = 4;
  void clear_basis();
  static const int kBasisFieldNumber = 4;
  const ::std::string& basis() const;
  void set_basis(const ::std::string& value);
  #if LANG_CXX11
  void set_basis(::std::string&& value);
  #endif
  void set_basis(const char* value);
  void set_basis(const char* value, size_t size);
  ::std::string* mutable_basis();
  ::std::string* release_basis();
  void set_allocated_basis(::std::string* basis);

  // .terachem_server.Mol mol = 1;
  bool has_mol() const;
  void clear_mol();
  static const int kMolFieldNumber = 1;
  const ::terachem_server::Mol& mol() const;
  ::terachem_server::Mol* mutable_mol();
  ::terachem_server::Mol* release_mol();
  void set_allocated_mol(::terachem_server::Mol* mol);

  // .terachem_server.JobInput.RunType run = 2;
  void clear_run();
  static const int kRunFieldNumber = 2;
  ::terachem_server::JobInput_RunType run() const;
  void set_run(::terachem_server::JobInput_RunType value);

  // .terachem_server.JobInput.MethodType method = 3;
  void clear_method();
  static const int kMethodFieldNumber = 3;
  ::terachem_server::JobInput_MethodType method() const;
  void set_method(::terachem_server::JobInput_MethodType value);

  // bool return_bond_order = 16;
  void clear_return_bond_order();
  static const int kReturnBondOrderFieldNumber = 16;
  bool return_bond_order() const;
  void set_return_bond_order(bool value);

  // @@protoc_insertion_point(class_scope:terachem_server.JobInput)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > guess_mo_coeffs_a_;
  mutable int _guess_mo_coeffs_a_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > guess_mo_coeffs_b_;
  mutable int _guess_mo_coeffs_b_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> user_options_;
  ::google::protobuf::internal::ArenaStringPtr basis_;
  ::terachem_server::Mol* mol_;
  int run_;
  int method_;
  bool return_bond_order_;
  mutable int _cached_size_;
  friend struct protobuf_terachem_5fserver_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class JobOutput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:terachem_server.JobOutput) */ {
 public:
  JobOutput();
  virtual ~JobOutput();

  JobOutput(const JobOutput& from);

  inline JobOutput& operator=(const JobOutput& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JobOutput& default_instance();

  static inline const JobOutput* internal_default_instance() {
    return reinterpret_cast<const JobOutput*>(
               &_JobOutput_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(JobOutput* other);

  // implements Message ----------------------------------------------

  inline JobOutput* New() const PROTOBUF_FINAL { return New(NULL); }

  JobOutput* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JobOutput& from);
  void MergeFrom(const JobOutput& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JobOutput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double gradient = 3;
  int gradient_size() const;
  void clear_gradient();
  static const int kGradientFieldNumber = 3;
  double gradient(int index) const;
  void set_gradient(int index, double value);
  void add_gradient(double value);
  const ::google::protobuf::RepeatedField< double >&
      gradient() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_gradient();

  // repeated double charges = 4;
  int charges_size() const;
  void clear_charges();
  static const int kChargesFieldNumber = 4;
  double charges(int index) const;
  void set_charges(int index, double value);
  void add_charges(double value);
  const ::google::protobuf::RepeatedField< double >&
      charges() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_charges();

  // repeated double spins = 5;
  int spins_size() const;
  void clear_spins();
  static const int kSpinsFieldNumber = 5;
  double spins(int index) const;
  void set_spins(int index, double value);
  void add_spins(double value);
  const ::google::protobuf::RepeatedField< double >&
      spins() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_spins();

  // repeated double dipoles = 6;
  int dipoles_size() const;
  void clear_dipoles();
  static const int kDipolesFieldNumber = 6;
  double dipoles(int index) const;
  void set_dipoles(int index, double value);
  void add_dipoles(double value);
  const ::google::protobuf::RepeatedField< double >&
      dipoles() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_dipoles();

  // repeated double mo_coeffs_a = 7;
  int mo_coeffs_a_size() const;
  void clear_mo_coeffs_a();
  static const int kMoCoeffsAFieldNumber = 7;
  double mo_coeffs_a(int index) const;
  void set_mo_coeffs_a(int index, double value);
  void add_mo_coeffs_a(double value);
  const ::google::protobuf::RepeatedField< double >&
      mo_coeffs_a() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_mo_coeffs_a();

  // repeated double mo_coeffs_b = 8;
  int mo_coeffs_b_size() const;
  void clear_mo_coeffs_b();
  static const int kMoCoeffsBFieldNumber = 8;
  double mo_coeffs_b(int index) const;
  void set_mo_coeffs_b(int index, double value);
  void add_mo_coeffs_b(double value);
  const ::google::protobuf::RepeatedField< double >&
      mo_coeffs_b() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_mo_coeffs_b();

  // repeated double bond_order = 16;
  int bond_order_size() const;
  void clear_bond_order();
  static const int kBondOrderFieldNumber = 16;
  double bond_order(int index) const;
  void set_bond_order(int index, double value);
  void add_bond_order(double value);
  const ::google::protobuf::RepeatedField< double >&
      bond_order() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_bond_order();

  // string job_dir = 9;
  void clear_job_dir();
  static const int kJobDirFieldNumber = 9;
  const ::std::string& job_dir() const;
  void set_job_dir(const ::std::string& value);
  #if LANG_CXX11
  void set_job_dir(::std::string&& value);
  #endif
  void set_job_dir(const char* value);
  void set_job_dir(const char* value, size_t size);
  ::std::string* mutable_job_dir();
  ::std::string* release_job_dir();
  void set_allocated_job_dir(::std::string* job_dir);

  // .terachem_server.Mol mol = 1;
  bool has_mol() const;
  void clear_mol();
  static const int kMolFieldNumber = 1;
  const ::terachem_server::Mol& mol() const;
  ::terachem_server::Mol* mutable_mol();
  ::terachem_server::Mol* release_mol();
  void set_allocated_mol(::terachem_server::Mol* mol);

  // double energy = 2;
  void clear_energy();
  static const int kEnergyFieldNumber = 2;
  double energy() const;
  void set_energy(double value);

  // @@protoc_insertion_point(class_scope:terachem_server.JobOutput)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > gradient_;
  mutable int _gradient_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > charges_;
  mutable int _charges_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > spins_;
  mutable int _spins_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > dipoles_;
  mutable int _dipoles_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > mo_coeffs_a_;
  mutable int _mo_coeffs_a_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > mo_coeffs_b_;
  mutable int _mo_coeffs_b_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > bond_order_;
  mutable int _bond_order_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr job_dir_;
  ::terachem_server::Mol* mol_;
  double energy_;
  mutable int _cached_size_;
  friend struct protobuf_terachem_5fserver_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Status

// bool busy = 1;
inline void Status::clear_busy() {
  busy_ = false;
}
inline bool Status::busy() const {
  // @@protoc_insertion_point(field_get:terachem_server.Status.busy)
  return busy_;
}
inline void Status::set_busy(bool value) {
  
  busy_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Status.busy)
}

// bool accepted = 2;
inline bool Status::has_accepted() const {
  return job_status_case() == kAccepted;
}
inline void Status::set_has_accepted() {
  _oneof_case_[0] = kAccepted;
}
inline void Status::clear_accepted() {
  if (has_accepted()) {
    job_status_.accepted_ = false;
    clear_has_job_status();
  }
}
inline bool Status::accepted() const {
  // @@protoc_insertion_point(field_get:terachem_server.Status.accepted)
  if (has_accepted()) {
    return job_status_.accepted_;
  }
  return false;
}
inline void Status::set_accepted(bool value) {
  if (!has_accepted()) {
    clear_job_status();
    set_has_accepted();
  }
  job_status_.accepted_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Status.accepted)
}

// bool working = 3;
inline bool Status::has_working() const {
  return job_status_case() == kWorking;
}
inline void Status::set_has_working() {
  _oneof_case_[0] = kWorking;
}
inline void Status::clear_working() {
  if (has_working()) {
    job_status_.working_ = false;
    clear_has_job_status();
  }
}
inline bool Status::working() const {
  // @@protoc_insertion_point(field_get:terachem_server.Status.working)
  if (has_working()) {
    return job_status_.working_;
  }
  return false;
}
inline void Status::set_working(bool value) {
  if (!has_working()) {
    clear_job_status();
    set_has_working();
  }
  job_status_.working_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Status.working)
}

// bool completed = 4;
inline bool Status::has_completed() const {
  return job_status_case() == kCompleted;
}
inline void Status::set_has_completed() {
  _oneof_case_[0] = kCompleted;
}
inline void Status::clear_completed() {
  if (has_completed()) {
    job_status_.completed_ = false;
    clear_has_job_status();
  }
}
inline bool Status::completed() const {
  // @@protoc_insertion_point(field_get:terachem_server.Status.completed)
  if (has_completed()) {
    return job_status_.completed_;
  }
  return false;
}
inline void Status::set_completed(bool value) {
  if (!has_completed()) {
    clear_job_status();
    set_has_completed();
  }
  job_status_.completed_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Status.completed)
}

inline bool Status::has_job_status() const {
  return job_status_case() != JOB_STATUS_NOT_SET;
}
inline void Status::clear_has_job_status() {
  _oneof_case_[0] = JOB_STATUS_NOT_SET;
}
inline Status::JobStatusCase Status::job_status_case() const {
  return Status::JobStatusCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Mol

// repeated string atoms = 1;
inline int Mol::atoms_size() const {
  return atoms_.size();
}
inline void Mol::clear_atoms() {
  atoms_.Clear();
}
inline const ::std::string& Mol::atoms(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.atoms)
  return atoms_.Get(index);
}
inline ::std::string* Mol::mutable_atoms(int index) {
  // @@protoc_insertion_point(field_mutable:terachem_server.Mol.atoms)
  return atoms_.Mutable(index);
}
inline void Mol::set_atoms(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:terachem_server.Mol.atoms)
  atoms_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Mol::set_atoms(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:terachem_server.Mol.atoms)
  atoms_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Mol::set_atoms(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  atoms_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:terachem_server.Mol.atoms)
}
inline void Mol::set_atoms(int index, const char* value, size_t size) {
  atoms_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:terachem_server.Mol.atoms)
}
inline ::std::string* Mol::add_atoms() {
  // @@protoc_insertion_point(field_add_mutable:terachem_server.Mol.atoms)
  return atoms_.Add();
}
inline void Mol::add_atoms(const ::std::string& value) {
  atoms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:terachem_server.Mol.atoms)
}
#if LANG_CXX11
inline void Mol::add_atoms(::std::string&& value) {
  atoms_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:terachem_server.Mol.atoms)
}
#endif
inline void Mol::add_atoms(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  atoms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:terachem_server.Mol.atoms)
}
inline void Mol::add_atoms(const char* value, size_t size) {
  atoms_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:terachem_server.Mol.atoms)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Mol::atoms() const {
  // @@protoc_insertion_point(field_list:terachem_server.Mol.atoms)
  return atoms_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Mol::mutable_atoms() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.Mol.atoms)
  return &atoms_;
}

// repeated double xyz = 2;
inline int Mol::xyz_size() const {
  return xyz_.size();
}
inline void Mol::clear_xyz() {
  xyz_.Clear();
}
inline double Mol::xyz(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.xyz)
  return xyz_.Get(index);
}
inline void Mol::set_xyz(int index, double value) {
  xyz_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.Mol.xyz)
}
inline void Mol::add_xyz(double value) {
  xyz_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.Mol.xyz)
}
inline const ::google::protobuf::RepeatedField< double >&
Mol::xyz() const {
  // @@protoc_insertion_point(field_list:terachem_server.Mol.xyz)
  return xyz_;
}
inline ::google::protobuf::RepeatedField< double >*
Mol::mutable_xyz() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.Mol.xyz)
  return &xyz_;
}

// .terachem_server.Mol.UnitType units = 3;
inline void Mol::clear_units() {
  units_ = 0;
}
inline ::terachem_server::Mol_UnitType Mol::units() const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.units)
  return static_cast< ::terachem_server::Mol_UnitType >(units_);
}
inline void Mol::set_units(::terachem_server::Mol_UnitType value) {
  
  units_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Mol.units)
}

// int32 charge = 4;
inline void Mol::clear_charge() {
  charge_ = 0;
}
inline ::google::protobuf::int32 Mol::charge() const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.charge)
  return charge_;
}
inline void Mol::set_charge(::google::protobuf::int32 value) {
  
  charge_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Mol.charge)
}

// int32 multiplicity = 5;
inline void Mol::clear_multiplicity() {
  multiplicity_ = 0;
}
inline ::google::protobuf::int32 Mol::multiplicity() const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.multiplicity)
  return multiplicity_;
}
inline void Mol::set_multiplicity(::google::protobuf::int32 value) {
  
  multiplicity_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Mol.multiplicity)
}

// bool closed = 6;
inline void Mol::clear_closed() {
  closed_ = false;
}
inline bool Mol::closed() const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.closed)
  return closed_;
}
inline void Mol::set_closed(bool value) {
  
  closed_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Mol.closed)
}

// bool restricted = 7;
inline void Mol::clear_restricted() {
  restricted_ = false;
}
inline bool Mol::restricted() const {
  // @@protoc_insertion_point(field_get:terachem_server.Mol.restricted)
  return restricted_;
}
inline void Mol::set_restricted(bool value) {
  
  restricted_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.Mol.restricted)
}

// -------------------------------------------------------------------

// JobInput

// .terachem_server.Mol mol = 1;
inline bool JobInput::has_mol() const {
  return this != internal_default_instance() && mol_ != NULL;
}
inline void JobInput::clear_mol() {
  if (GetArenaNoVirtual() == NULL && mol_ != NULL) delete mol_;
  mol_ = NULL;
}
inline const ::terachem_server::Mol& JobInput::mol() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.mol)
  return mol_ != NULL ? *mol_
                         : *::terachem_server::Mol::internal_default_instance();
}
inline ::terachem_server::Mol* JobInput::mutable_mol() {
  
  if (mol_ == NULL) {
    mol_ = new ::terachem_server::Mol;
  }
  // @@protoc_insertion_point(field_mutable:terachem_server.JobInput.mol)
  return mol_;
}
inline ::terachem_server::Mol* JobInput::release_mol() {
  // @@protoc_insertion_point(field_release:terachem_server.JobInput.mol)
  
  ::terachem_server::Mol* temp = mol_;
  mol_ = NULL;
  return temp;
}
inline void JobInput::set_allocated_mol(::terachem_server::Mol* mol) {
  delete mol_;
  mol_ = mol;
  if (mol) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:terachem_server.JobInput.mol)
}

// .terachem_server.JobInput.RunType run = 2;
inline void JobInput::clear_run() {
  run_ = 0;
}
inline ::terachem_server::JobInput_RunType JobInput::run() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.run)
  return static_cast< ::terachem_server::JobInput_RunType >(run_);
}
inline void JobInput::set_run(::terachem_server::JobInput_RunType value) {
  
  run_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.run)
}

// .terachem_server.JobInput.MethodType method = 3;
inline void JobInput::clear_method() {
  method_ = 0;
}
inline ::terachem_server::JobInput_MethodType JobInput::method() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.method)
  return static_cast< ::terachem_server::JobInput_MethodType >(method_);
}
inline void JobInput::set_method(::terachem_server::JobInput_MethodType value) {
  
  method_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.method)
}

// string basis = 4;
inline void JobInput::clear_basis() {
  basis_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JobInput::basis() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.basis)
  return basis_.GetNoArena();
}
inline void JobInput::set_basis(const ::std::string& value) {
  
  basis_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.basis)
}
#if LANG_CXX11
inline void JobInput::set_basis(::std::string&& value) {
  
  basis_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:terachem_server.JobInput.basis)
}
#endif
inline void JobInput::set_basis(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  basis_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:terachem_server.JobInput.basis)
}
inline void JobInput::set_basis(const char* value, size_t size) {
  
  basis_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:terachem_server.JobInput.basis)
}
inline ::std::string* JobInput::mutable_basis() {
  
  // @@protoc_insertion_point(field_mutable:terachem_server.JobInput.basis)
  return basis_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JobInput::release_basis() {
  // @@protoc_insertion_point(field_release:terachem_server.JobInput.basis)
  
  return basis_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JobInput::set_allocated_basis(::std::string* basis) {
  if (basis != NULL) {
    
  } else {
    
  }
  basis_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), basis);
  // @@protoc_insertion_point(field_set_allocated:terachem_server.JobInput.basis)
}

// repeated double guess_mo_coeffs_a = 5;
inline int JobInput::guess_mo_coeffs_a_size() const {
  return guess_mo_coeffs_a_.size();
}
inline void JobInput::clear_guess_mo_coeffs_a() {
  guess_mo_coeffs_a_.Clear();
}
inline double JobInput::guess_mo_coeffs_a(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.guess_mo_coeffs_a)
  return guess_mo_coeffs_a_.Get(index);
}
inline void JobInput::set_guess_mo_coeffs_a(int index, double value) {
  guess_mo_coeffs_a_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.guess_mo_coeffs_a)
}
inline void JobInput::add_guess_mo_coeffs_a(double value) {
  guess_mo_coeffs_a_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobInput.guess_mo_coeffs_a)
}
inline const ::google::protobuf::RepeatedField< double >&
JobInput::guess_mo_coeffs_a() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobInput.guess_mo_coeffs_a)
  return guess_mo_coeffs_a_;
}
inline ::google::protobuf::RepeatedField< double >*
JobInput::mutable_guess_mo_coeffs_a() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobInput.guess_mo_coeffs_a)
  return &guess_mo_coeffs_a_;
}

// repeated double guess_mo_coeffs_b = 6;
inline int JobInput::guess_mo_coeffs_b_size() const {
  return guess_mo_coeffs_b_.size();
}
inline void JobInput::clear_guess_mo_coeffs_b() {
  guess_mo_coeffs_b_.Clear();
}
inline double JobInput::guess_mo_coeffs_b(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.guess_mo_coeffs_b)
  return guess_mo_coeffs_b_.Get(index);
}
inline void JobInput::set_guess_mo_coeffs_b(int index, double value) {
  guess_mo_coeffs_b_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.guess_mo_coeffs_b)
}
inline void JobInput::add_guess_mo_coeffs_b(double value) {
  guess_mo_coeffs_b_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobInput.guess_mo_coeffs_b)
}
inline const ::google::protobuf::RepeatedField< double >&
JobInput::guess_mo_coeffs_b() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobInput.guess_mo_coeffs_b)
  return guess_mo_coeffs_b_;
}
inline ::google::protobuf::RepeatedField< double >*
JobInput::mutable_guess_mo_coeffs_b() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobInput.guess_mo_coeffs_b)
  return &guess_mo_coeffs_b_;
}

// repeated string user_options = 7;
inline int JobInput::user_options_size() const {
  return user_options_.size();
}
inline void JobInput::clear_user_options() {
  user_options_.Clear();
}
inline const ::std::string& JobInput::user_options(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.user_options)
  return user_options_.Get(index);
}
inline ::std::string* JobInput::mutable_user_options(int index) {
  // @@protoc_insertion_point(field_mutable:terachem_server.JobInput.user_options)
  return user_options_.Mutable(index);
}
inline void JobInput::set_user_options(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.user_options)
  user_options_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void JobInput::set_user_options(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.user_options)
  user_options_.Mutable(index)->assign(std::move(value));
}
#endif
inline void JobInput::set_user_options(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_options_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:terachem_server.JobInput.user_options)
}
inline void JobInput::set_user_options(int index, const char* value, size_t size) {
  user_options_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:terachem_server.JobInput.user_options)
}
inline ::std::string* JobInput::add_user_options() {
  // @@protoc_insertion_point(field_add_mutable:terachem_server.JobInput.user_options)
  return user_options_.Add();
}
inline void JobInput::add_user_options(const ::std::string& value) {
  user_options_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobInput.user_options)
}
#if LANG_CXX11
inline void JobInput::add_user_options(::std::string&& value) {
  user_options_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:terachem_server.JobInput.user_options)
}
#endif
inline void JobInput::add_user_options(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_options_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:terachem_server.JobInput.user_options)
}
inline void JobInput::add_user_options(const char* value, size_t size) {
  user_options_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:terachem_server.JobInput.user_options)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
JobInput::user_options() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobInput.user_options)
  return user_options_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
JobInput::mutable_user_options() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobInput.user_options)
  return &user_options_;
}

// bool return_bond_order = 16;
inline void JobInput::clear_return_bond_order() {
  return_bond_order_ = false;
}
inline bool JobInput::return_bond_order() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobInput.return_bond_order)
  return return_bond_order_;
}
inline void JobInput::set_return_bond_order(bool value) {
  
  return_bond_order_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.JobInput.return_bond_order)
}

// -------------------------------------------------------------------

// JobOutput

// .terachem_server.Mol mol = 1;
inline bool JobOutput::has_mol() const {
  return this != internal_default_instance() && mol_ != NULL;
}
inline void JobOutput::clear_mol() {
  if (GetArenaNoVirtual() == NULL && mol_ != NULL) delete mol_;
  mol_ = NULL;
}
inline const ::terachem_server::Mol& JobOutput::mol() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.mol)
  return mol_ != NULL ? *mol_
                         : *::terachem_server::Mol::internal_default_instance();
}
inline ::terachem_server::Mol* JobOutput::mutable_mol() {
  
  if (mol_ == NULL) {
    mol_ = new ::terachem_server::Mol;
  }
  // @@protoc_insertion_point(field_mutable:terachem_server.JobOutput.mol)
  return mol_;
}
inline ::terachem_server::Mol* JobOutput::release_mol() {
  // @@protoc_insertion_point(field_release:terachem_server.JobOutput.mol)
  
  ::terachem_server::Mol* temp = mol_;
  mol_ = NULL;
  return temp;
}
inline void JobOutput::set_allocated_mol(::terachem_server::Mol* mol) {
  delete mol_;
  mol_ = mol;
  if (mol) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:terachem_server.JobOutput.mol)
}

// double energy = 2;
inline void JobOutput::clear_energy() {
  energy_ = 0;
}
inline double JobOutput::energy() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.energy)
  return energy_;
}
inline void JobOutput::set_energy(double value) {
  
  energy_ = value;
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.energy)
}

// repeated double gradient = 3;
inline int JobOutput::gradient_size() const {
  return gradient_.size();
}
inline void JobOutput::clear_gradient() {
  gradient_.Clear();
}
inline double JobOutput::gradient(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.gradient)
  return gradient_.Get(index);
}
inline void JobOutput::set_gradient(int index, double value) {
  gradient_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.gradient)
}
inline void JobOutput::add_gradient(double value) {
  gradient_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.gradient)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::gradient() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.gradient)
  return gradient_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_gradient() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.gradient)
  return &gradient_;
}

// repeated double charges = 4;
inline int JobOutput::charges_size() const {
  return charges_.size();
}
inline void JobOutput::clear_charges() {
  charges_.Clear();
}
inline double JobOutput::charges(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.charges)
  return charges_.Get(index);
}
inline void JobOutput::set_charges(int index, double value) {
  charges_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.charges)
}
inline void JobOutput::add_charges(double value) {
  charges_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.charges)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::charges() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.charges)
  return charges_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_charges() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.charges)
  return &charges_;
}

// repeated double spins = 5;
inline int JobOutput::spins_size() const {
  return spins_.size();
}
inline void JobOutput::clear_spins() {
  spins_.Clear();
}
inline double JobOutput::spins(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.spins)
  return spins_.Get(index);
}
inline void JobOutput::set_spins(int index, double value) {
  spins_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.spins)
}
inline void JobOutput::add_spins(double value) {
  spins_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.spins)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::spins() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.spins)
  return spins_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_spins() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.spins)
  return &spins_;
}

// repeated double dipoles = 6;
inline int JobOutput::dipoles_size() const {
  return dipoles_.size();
}
inline void JobOutput::clear_dipoles() {
  dipoles_.Clear();
}
inline double JobOutput::dipoles(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.dipoles)
  return dipoles_.Get(index);
}
inline void JobOutput::set_dipoles(int index, double value) {
  dipoles_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.dipoles)
}
inline void JobOutput::add_dipoles(double value) {
  dipoles_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.dipoles)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::dipoles() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.dipoles)
  return dipoles_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_dipoles() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.dipoles)
  return &dipoles_;
}

// repeated double mo_coeffs_a = 7;
inline int JobOutput::mo_coeffs_a_size() const {
  return mo_coeffs_a_.size();
}
inline void JobOutput::clear_mo_coeffs_a() {
  mo_coeffs_a_.Clear();
}
inline double JobOutput::mo_coeffs_a(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.mo_coeffs_a)
  return mo_coeffs_a_.Get(index);
}
inline void JobOutput::set_mo_coeffs_a(int index, double value) {
  mo_coeffs_a_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.mo_coeffs_a)
}
inline void JobOutput::add_mo_coeffs_a(double value) {
  mo_coeffs_a_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.mo_coeffs_a)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::mo_coeffs_a() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.mo_coeffs_a)
  return mo_coeffs_a_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_mo_coeffs_a() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.mo_coeffs_a)
  return &mo_coeffs_a_;
}

// repeated double mo_coeffs_b = 8;
inline int JobOutput::mo_coeffs_b_size() const {
  return mo_coeffs_b_.size();
}
inline void JobOutput::clear_mo_coeffs_b() {
  mo_coeffs_b_.Clear();
}
inline double JobOutput::mo_coeffs_b(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.mo_coeffs_b)
  return mo_coeffs_b_.Get(index);
}
inline void JobOutput::set_mo_coeffs_b(int index, double value) {
  mo_coeffs_b_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.mo_coeffs_b)
}
inline void JobOutput::add_mo_coeffs_b(double value) {
  mo_coeffs_b_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.mo_coeffs_b)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::mo_coeffs_b() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.mo_coeffs_b)
  return mo_coeffs_b_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_mo_coeffs_b() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.mo_coeffs_b)
  return &mo_coeffs_b_;
}

// string job_dir = 9;
inline void JobOutput::clear_job_dir() {
  job_dir_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JobOutput::job_dir() const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.job_dir)
  return job_dir_.GetNoArena();
}
inline void JobOutput::set_job_dir(const ::std::string& value) {
  
  job_dir_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.job_dir)
}
#if LANG_CXX11
inline void JobOutput::set_job_dir(::std::string&& value) {
  
  job_dir_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:terachem_server.JobOutput.job_dir)
}
#endif
inline void JobOutput::set_job_dir(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  job_dir_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:terachem_server.JobOutput.job_dir)
}
inline void JobOutput::set_job_dir(const char* value, size_t size) {
  
  job_dir_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:terachem_server.JobOutput.job_dir)
}
inline ::std::string* JobOutput::mutable_job_dir() {
  
  // @@protoc_insertion_point(field_mutable:terachem_server.JobOutput.job_dir)
  return job_dir_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JobOutput::release_job_dir() {
  // @@protoc_insertion_point(field_release:terachem_server.JobOutput.job_dir)
  
  return job_dir_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JobOutput::set_allocated_job_dir(::std::string* job_dir) {
  if (job_dir != NULL) {
    
  } else {
    
  }
  job_dir_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), job_dir);
  // @@protoc_insertion_point(field_set_allocated:terachem_server.JobOutput.job_dir)
}

// repeated double bond_order = 16;
inline int JobOutput::bond_order_size() const {
  return bond_order_.size();
}
inline void JobOutput::clear_bond_order() {
  bond_order_.Clear();
}
inline double JobOutput::bond_order(int index) const {
  // @@protoc_insertion_point(field_get:terachem_server.JobOutput.bond_order)
  return bond_order_.Get(index);
}
inline void JobOutput::set_bond_order(int index, double value) {
  bond_order_.Set(index, value);
  // @@protoc_insertion_point(field_set:terachem_server.JobOutput.bond_order)
}
inline void JobOutput::add_bond_order(double value) {
  bond_order_.Add(value);
  // @@protoc_insertion_point(field_add:terachem_server.JobOutput.bond_order)
}
inline const ::google::protobuf::RepeatedField< double >&
JobOutput::bond_order() const {
  // @@protoc_insertion_point(field_list:terachem_server.JobOutput.bond_order)
  return bond_order_;
}
inline ::google::protobuf::RepeatedField< double >*
JobOutput::mutable_bond_order() {
  // @@protoc_insertion_point(field_mutable_list:terachem_server.JobOutput.bond_order)
  return &bond_order_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace terachem_server

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::terachem_server::Mol_UnitType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::terachem_server::Mol_UnitType>() {
  return ::terachem_server::Mol_UnitType_descriptor();
}
template <> struct is_proto_enum< ::terachem_server::JobInput_RunType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::terachem_server::JobInput_RunType>() {
  return ::terachem_server::JobInput_RunType_descriptor();
}
template <> struct is_proto_enum< ::terachem_server::JobInput_MethodType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::terachem_server::JobInput_MethodType>() {
  return ::terachem_server::JobInput_MethodType_descriptor();
}
template <> struct is_proto_enum< ::terachem_server::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::terachem_server::MessageType>() {
  return ::terachem_server::MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_terachem_5fserver_2eproto__INCLUDED
